### ISSUE TITLE
4xx response body is null

### ISSUE THREAD

**Issue by ngot** [asos-craigmorten/superdeno#1]
# Issue

Setup:

- deno 1.0.5
- v8 8.4.300
- typescript 3.9.2

4xx response body is null, even though there is a response body.

## Details

I want to test the custom response body, but there is nothing in res body.

By the way, when responding 4xx, superdeno also throws error which is different from supertest, which is annoying.

**Comment by asos-craigmorten** [comment]
Hmm, this is actually an issue that has impacted supertest on several occasions, see:

- https://github.com/visionmedia/supertest/issues/556
- https://github.com/visionmedia/supertest/issues/559

And is generally as a result of the underlying `superagent` library having an issue, e.g.:

- https://github.com/visionmedia/superagent/issues/1466

It looks like we're using a later version of `sugeragent` than `supertest` is, when I next have time I'll see if matching the versions solves it.

Do you have a minimal reproducible code example that can be used (e.g. server and test you're trying to run)?

**Comment by ngot** [comment]
It can be reproduced by:

```js
import {
  Application,
} from "https://deno.land/x/ako/mod.ts";
import { superdeno } from "https://deno.land/x/superdeno@1.1.2/mod.ts";
import { describe, it } from "https://deno.land/x/opine@0.8.0/test/utils.ts";
import {
  assert,
  assertEquals,
} from "https://deno.land/std@0.53.0/testing/asserts.ts";

describe("ctx.onerror(err)", () => {
  it("should respond", (done) => {
    const app = new Application();

    app.use((ctx, next) => {
      ctx.body = "something else";

      ctx.throw(418, "boom");
    });

    const server = app.listen();

    superdeno(server)
      .head("/")
      .expect(418)
      .expect("Content-Length", "4")
      .expect("Content-Type", "text/plain; charset=utf-8")
      .end((err, res) => {
        assertEquals(err.message, "I'm a teapot");
        assertEquals(res.status, 418);
        // TODO: https://github.com/asos-craigmorten/superdeno/issues/1
        // assertEquals(res.text, "boom");
        done();
      });
  });
});

```

According to https://github.com/visionmedia/superagent/pull/1468, seems like it was fixed. I will try to fix it this week sometime.

**Comment by asos-craigmorten** [comment]
Taking a look at this. Added a simple unit test for `.expect(400)` and seeing:

```console
error: Uncaught Error: Bad Request
          new_err = new Error(res.statusText || res.text || 'Unsuccessful HTTP response');
                    ^
    at Test.<anonymous> (https://dev.jspm.io/npm:superagent@5.2.2/lib/client.dew.js:475:21)
    at Test.Emitter.emit (https://dev.jspm.io/npm:component-emitter@1.3.0/index.dew.js:148:22)
    at XMLHttpRequestSham.xhr.onreadystatechange (https://dev.jspm.io/npm:superagent@5.2.2/lib/client.dew.js:784:12)
    at XMLHttpRequestSham.xhrReceive (file:///Users/craig.morten/git/asos-craigmorten/superdeno/src/xhrSham.js:105:29)
    at file:///Users/craig.morten/git/asos-craigmorten/superdeno/src/xhrSham.js:52:21
    at Object.xhr.onreadystatechange (file:///Users/craig.morten/git/asos-craigmorten/superdeno/src/xhrSham.js:186:7)
    at XMLHttpRequestSham.xhrSend (file:///Users/craig.morten/git/asos-craigmorten/superdeno/src/xhrSham.js:287:9)
    at async XMLHttpRequestSham.send (file:///Users/craig.morten/git/asos-craigmorten/superdeno/src/xhrSham.js:51:7)
```

The referenced line is here --> https://github.com/visionmedia/superagent/blob/master/src/client.js#L468

Introduced in https://github.com/visionmedia/superagent/pull/1473

---

I can confirm that isn't an issue with latest `supertest` having tried to reproduce with:

```js
const express = require("express");
const request = require("supertest");

const app = express();

app.get("/", (req, res, next) => {
  res.sendStatus(400);
});

request(app)
  .get("/")
  .expect(400)
  .end((err, res) => {
    if (err) throw err;
  });
```

So it is something different with SuperDeno. The version of `superagent` is different, so going to try downgrading to `5.1.0` to match `supertest`.

**Comment by asos-craigmorten** [comment]
Thanks for raising this @ngot 😄 found the bug and should be fixed in latest version! 🎉

**Comment by asos-craigmorten** [comment]
Let me know if still encountering any issues!
