### ISSUE TITLE
4xx and 5xx response missing body and text

### ISSUE THREAD

**Issue by ngot** [asos-craigmorten/superdeno#11]
# Issue

Setup:

- deno 1.0.5
- v8 8.4.300
- typescript 3.9.2

When server response 4xx or 5xx, superdeno's response doesn't have body or text, so there is no way to test the HTTP body part.

```js
import {
  Application,
} from "https://deno.land/x/ako/mod.ts";
import { superdeno } from "https://deno.land/x/superdeno@1.5.1/mod.ts";
import { describe, it } from "https://deno.land/x/opine@0.17.0/test/utils.ts";

describe("ctx.onerror(err)", () => {
  it("should respond", async () => {
    const app = new Application();

    app.use((ctx, next) => {
      ctx.body = "something else";

      ctx.throw(418, "boom");
    });

    const res = await superdeno(app.listen())
      .head("/")
      .expect(418)
      .expect("Content-Length", "4")
      .expect("Content-Type", "text/plain; charset=utf-8");
    console.log(res);

    // res.body is null
    // res.text is null
  });
});
```

curl:

```bash
curl -i  127.0.0.1:5000
HTTP/1.1 418 I'm a teapot
content-length: 4
content-type: text/plain; charset=utf-8

boom% 
```

**Comment by ngot** [comment]
Read https://github.com/asos-craigmorten/superdeno/issues/1 again, realized that patch only fixes the error throw, not the empty body.

**Comment by asos-craigmorten** [comment]
Hi @ngot I've added a test for this for both Oak and Ako in `1.6.0`.

I believe the issue is that in the sample test you are making a `HEAD` request which will discard the body, whereas in your `curl` request you are implicitly using a `GET` request, so the body is returned.

Test added here: https://github.com/asos-craigmorten/superdeno/blob/main/test/supertest.ako.test.ts#L7 and passing in CICD.

**Comment by ngot** [comment]
@asos-craigmorten Thanks for the investigation. That's right, I didn't realise I was using the HEAD request. I was definitely not too blind to find that.

**Comment by asos-craigmorten** [comment]
No worries - thanks for raising anyway! Lead to some extra tests and a small refactor so all good 🎉
