### ISSUE TITLE
Consider using Pagic to build the website?

### ISSUE THREAD

**Issue by xcatliu** [asos-craigmorten/superdeno#17]
[Pagic](https://pagic.org) is a static site generator powered by Deno + React

Here are some demos:

- [pagic.org](https://pagic.org)
- [Deno X ranking](https://yoshixmk.github.io/deno-x-ranking/)
- [TypeScript 入门教程](https://ts.xcatliu.com/)

Ask me anything if you have some problem.

**Comment by asos-craigmorten** [comment]
Hey @xcatliu, I think the current docs setup is ok for SuperDeno.

If / when users raise issues for greater doc clarity that demands something outside of the GitHub Pages ecosystem I will be sure to look at Page :smile:.
