### ISSUE TITLE
Question: testing if header doesn't exist

### ISSUE THREAD

**Issue by talentlessguy** [asos-craigmorten/superdeno#30]
# Issue

Setup:

deno 1.12.0 (release, x86_64-unknown-linux-gnu)
v8 9.2.230.14
typescript 4.3.2
- SuperDeno Version: 4.4.0

## Details

At the moment this:

```ts
import { superdeno } from 'https://deno.land/x/superdeno@4.4.0/mod.ts'
import { App } from 'https://deno.land/x/tinyhttp/mod.ts'
import { describe, it, expect, run } from 'https://deno.land/x/tincan@0.2.1/mod.ts'

describe('App settings', () => {
it('when disabled should not send anything', async () => {

const app = new App({ settings: { xPoweredBy: false } })

    app.use((_req, res) => void res.send('hi'))

    const request = superdeno(app.attach)

    await request.get('/').expect('X-Powered-By', null)

})
})

run()
```

results in this:

```
Error: expected "X-Powered-By" header field
    at Test.#assertHeader (https://deno.land/x/superdeno@4.4.0/src/test.ts:562:14)
    at Test.#assertFunction (https://deno.land/x/superdeno@4.4.0/src/test.ts:617:13)
    at Test.#assert (https://deno.land/x/superdeno@4.4.0/src/test.ts:480:35)
    at https://deno.land/x/superdeno@4.4.0/src/test.ts:455:23
    at async close (https://deno.land/x/superdeno@4.4.0/src/close.ts:48:46)

failures:

        App settings > xPoweredBy > when disabled should not send anything

test result: FAILED. 101 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (2657ms)

```

What's the proper way to test for absence of a header?

**Comment by cmorten** [comment]
Hi @talentlessguy 👋 

superdeno ports supertest and inherits it’s API. For now there is no dedicated `expect` method for asserting on the absence of a header.

Instead you can get access to the response and subsequently headers within `.end(_error, response)`.

REFs:
- https://github.com/visionmedia/supertest/issues/284
- https://stackoverflow.com/questions/33037327/how-to-check-not-exist-header-field-with-supertest

Alternatively you can `await` the response as the return value from a superdeno chain. Just note that you cannot use both `.end()` and `.then()` ( equivalently just `await`ing the response) on the same chain - it’s one or the other IIRC.

**Comment by asos-craigmorten** [comment]
Let me know if require further information and can re-open.
